CREATE TABLE CLIENT
(
  USER_NAME VARCHAR(20) NOT NULL 
, IS_ADMIN BOOLEAN NOT NULL 
, CONSTRAINT CLIENT_PK PRIMARY KEY 
  (
    USER_NAME
  )
);

INSERT INTO CLIENT
VALUES ('Adele', false);

INSERT INTO CLIENT
VALUES ('P.Eva ', true);


CREATE TABLE TICKET
(
  ID_TICKET INT NOT NULL
, ID_FLIGHT INT NOT NULL
, PRICE INT NOT NULL
, RIGHT_FIRST_SITTING BOOLEAN NOT NULL 
, RIGHT_FIRST_REGISTRATION BOOLEAN NOT NULL
, CONSTRAINT TICKET_PK PRIMARY KEY 
  (
    ID_TICKET
  )
);

INSERT INTO TICKET
VALUES (120, 3000, 99, true, true);

INSERT INTO TICKET
VALUES (121, 3010, 500, false, false);

CREATE TABLE FLIGHT
(
  ID_FLIGHT INT NOT NULL
, FROM_PLACE VARCHAR(20) NOT NULL
, TO_PLACE VARCHAR(20) NOT NULL
, DEPARTURE_TIME VARCHAR(20) NOT NULL
, ARRIVAL_TIME VARCHAR(20) NOT NULL
, PASSANGERS_AMOUNT INT NOT NULL
, CONSTRAINT FLIGHT_PK PRIMARY KEY 
  (
    ID_FLIGHT
  )
);

INSERT INTO FLIGHT
VALUES (3010, 'MINSK', 'PARIS', '2020-01-13 18:00', '2020-01-13 21:30', 981);

INSERT INTO FLIGHT
VALUES (3013, 'PARIS', 'MINSK', '2020-02-13 18:00', '2020-02-13 22:30', 981);

ALTER TABLE TICKET ADD CONSTRAINT fk_TICKET_ID_FLIGHT FOREIGN KEY(ID_FLIGHT)
REFERENCES FLIGHT (ID_FLIGHT);